export const defaultTasks = [
  {
    id: 1,
    title: "Brand Logo Design",
    description: "Make a redesign of the logo in corporate colors.",
    status: "todo",
    priority: "High",
    date: "Jun 17",
  },
  {
    id: 2,
    title: "New Header Image",
    description: "Create a modern header image.",
    status: "todo",
    priority: "Medium",
    date: "Jun 17",
  },
  {
    id: 3,
    title: "Wireframe for App",
    description: "Design wireframe before presentation.",
    status: "todo",
    priority: "Low",
    date: "Jun 17",
  },
  {
    id: 4,
    title: "Updating Modules",
    description: "Update dashboard modules.",
    status: "progress",
    priority: "High",
    date: "Jun 17",
  },
  {
    id: 5,
    title: "Template Progress",
    description: "Finish dashboard templates.",
    status: "progress",
    priority: "Medium",
    date: "Jun 17",
  },
  {
    id: 6,
    title: "Refresh Photo Slider",
    description: "Improve slider.",
    status: "completed",
    priority: "Low",
    date: "Jun 17",
  },
  {
  id: 7,
  title: "Server Startup",
  description: "Running the server in test mode and configuring.",
  status: "completed",
  date: "Jun 17",
  attachments: 0,
  comments: 17,
},
{
  id: 8,
  title: "New Background",
  description: "Background image approved.",
  status: "completed",
  date: "Jun 17",
  attachments: 1,
  comments: 2,
},
];