export const defaultCustomers = [
  {
    id: 1,
    name: "Regina Cooper",
    email: "cooper@example.com",
    location: "Sochi, Russia",
    phone: "+1 (070) 123-4567",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=1",
  },
  {
    id: 2,
    name: "Judith Black",
    email: "black@example.com",
    location: "Paris, France",
    phone: "+1 (070) 123-8459",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=2",
  },
  {
    id: 3,
    name: "Ronald Robertson",
    email: "robe@example.com",
    location: "Sydney, Australia",
    phone: "+1 (070) 123-9221",
    date: "12.09.20",
    status: "Blocked",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=3",
  },
  {
    id: 4,
    name: "Dustin Williamson",
    email: "williams@example.com",
    location: "Berlin, Germany",
    phone: "+1 (070) 123-0507",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=4",
  },
  {
    id: 5,
    name: "Calvin Flores",
    email: "flores@example.com",
    location: "New York, USA",
    phone: "+1 (070) 123-3791",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=5",
  },
  {
    id: 6,
    name: "Robert Edwards",
    email: "edwards@example.com",
    location: "Shanghai, China",
    phone: "+1 (070) 123-1147",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=6",
  },
  {
    id: 7,
    name: "Colleen Warren",
    email: "warren@example.com",
    location: "Ottawa, Canada",
    phone: "+1 (070) 123-9127",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=7",
  },
  {
    id: 8,
    name: "Nathan Fox",
    email: "fox@example.com",
    location: "London, UK",
    phone: "+1 (070) 123-5073",
    date: "12.09.20",
    status: "Active",
    checked: false,
    avatar: "https://i.pravatar.cc/100?img=8",
  },
];