export const defaultProducts = [
  {
    id: 1,
    name: "MacBook Pro 15 Retina Touch Bar MV902",
    productNo: "#790841",
    category: "Notebook",
    date: "12.09.20",
    price: "$2,500",
    status: "Available",
    checked: false,
    image: "",
    stock: 35,
  },
  {
    id: 2,
    name: "Apple Watch Series 5 Edition GPS + Cellular",
    productNo: "#790842",
    category: "Watch",
    date: "12.09.20",
    price: "$2,500",
    status: "Available",
    checked: false,
    image: "",
    stock: 18,
  },
  {
    id: 3,
    name: "Apple iPhone 11 Pro Max 256GB Space Gray",
    productNo: "#790843",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
    status: "Available",
    checked: false,
    image: "",
    stock: 42,
  },
  {
    id: 4,
    name: "Apple Watch Series 5 Edition GPS + Cellular",
    productNo: "#790844",
    category: "Watch",
    date: "12.09.20",
    price: "$2,500",
    status: "Available",
    checked: false,
    image: "",
    stock: 24,
  },
  {
    id: 5,
    name: "MacBook Pro 15 Retina Touch Bar MV902",
    productNo: "#790845",
    category: "Notebook",
    date: "12.09.20",
    price: "$2,500",
    status: "Disabled",
    checked: false,
    image: "",
    stock: 0,
  },
  {
    id: 6,
    name: "Apple iPhone 11 Pro Max 64GB Midnight Green",
    productNo: "#790846",
    category: "Phone",
    date: "12.09.20",
    price: "$2,500",
    status: "Disabled",
    checked: false,
    image: "",
    stock: 0,
  },
  {
    id: 7,
    name: "MacBook Pro 15 Retina Touch Bar MV902",
    productNo: "#790847",
    category: "Notebook",
    date: "12.09.20",
    price: "$2,500",
    status: "Available",
    checked: false,
    image: "",
    stock: 15,
  },
  {
    id: 8,
    name: "Apple Watch Series 5 Edition GPS + Cellular",
    productNo: "#790848",
    category: "Watch",
    date: "12.09.20",
    price: "$2,500",
    status: "Available",
    checked: false,
    image: "",
    stock: 28,
  },
];