import { useState } from "react";
import { FiDownload } from "react-icons/fi";
import { jsPDF } from "jspdf";
import toast from "react-hot-toast";

const OverviewHeader = () => {
  const [period, setPeriod] = useState("Last 7 Days");

  const handleDownload = () => {
    try {
      const doc = new jsPDF("p", "mm", "a4");

      // =========================
      // Header
      // =========================
      doc.setFillColor(33, 148, 58);
      doc.rect(0, 0, 210, 28, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(255, 255, 255);

      doc.text("Dashboard Report", 105, 18, {
        align: "center",
      });

      // =========================
      // Date
      // =========================
      doc.setTextColor(70);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);

      doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        15,
        40
      );

      doc.text(
        `Period: ${period}`,
        150,
        40
      );

      doc.line(15, 45, 195, 45);

      // =========================
      // Overview
      // =========================
      doc.setFontSize(17);
      doc.setFont("helvetica", "bold");

      doc.text("Overview", 15, 60);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);

      doc.text("Total Income", 20, 75);
      doc.text("$8,500", 160, 75);

      doc.text("Total Sales", 20, 87);
      doc.text("3,500K", 160, 87);

      doc.text("New Clients", 20, 99);
      doc.text("2,500K", 160, 99);

      doc.line(15, 108, 195, 108);

      // =========================
      // Statistics
      // =========================
      doc.setFont("helvetica", "bold");
      doc.setFontSize(17);

      doc.text("Statistics", 15, 123);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);

      doc.text(
        "Revenue increased steadily during this reporting period.",
        20,
        138
      );

      doc.text(
        "Overall business performance remains positive.",
        20,
        146
      );

      doc.line(15, 154, 195, 154);

      // =========================
      // Analytics
      // =========================
      doc.setFont("helvetica", "bold");
      doc.setFontSize(17);

      doc.text("Analytics", 15, 170);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);

      doc.text(
        "User engagement continues to improve.",
        20,
        185
      );

      doc.text(
        "Sales conversion has increased compared to last week.",
        20,
        193
      );

      doc.line(15, 201, 195, 201);

      // =========================
      // Last Orders
      // =========================
      doc.setFont("helvetica", "bold");
      doc.setFontSize(17);

      doc.text("Recent Orders", 15, 217);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);

      doc.text("Regina Cooper", 20, 231);
      doc.text("$2,500", 160, 231);

      doc.text("Robert Edwards", 20, 239);
      doc.text("$1,500", 160, 239);

      doc.text("Gloria Mckinney", 20, 247);
      doc.text("$5,600", 160, 247);

      doc.text("Randall Fisher", 20, 255);
      doc.text("$2,850", 160, 255);

      // =========================
      // Footer
      // =========================
      doc.setFillColor(245, 245, 245);
      doc.rect(0, 282, 210, 15, "F");

      doc.setFontSize(10);
      doc.setTextColor(100);

      doc.text(
        "Generated by Dashboard",
        15,
        291
      );

      doc.text(
        "Page 1",
        185,
        291
      );

      doc.save("Dashboard_Report.pdf");

      toast.success("Dashboard Report Downloaded");
    } catch (error) {
      console.error(error);
      toast.error("Download failed");
    }
  };

  return (
    <div className="flex items-center justify-between mb-6">

      <h1 className="text-3xl font-semibold text-gray-800">
        Overview
      </h1>

      <div className="flex items-center gap-3">

        <button
          onClick={handleDownload}
          className="w-11 h-11 rounded-xl border bg-white shadow hover:bg-[#21943A] hover:text-white transition flex items-center justify-center"
        >
          <FiDownload size={18} />
        </button>

        <select
          value={period}
          onChange={(e) => setPeriod(e.target.value)}
          className="h-11 rounded-xl border border-gray-200 bg-white px-4 outline-none"
        >
          <option>Today</option>
          <option>Yesterday</option>
          <option>Last 7 Days</option>
          <option>Last 30 Days</option>
          <option>This Month</option>
          <option>Last Month</option>
        </select>

      </div>

    </div>
  );
};

export default OverviewHeader;